### ISSUE TITLE
Переименовать репозиторий

### ISSUE THREAD

**Issue by ak-itacademy** [Svichkariov/review-of-comments#1]
Необходимо переименовать репозиторий.
Во-первых, не стоит использовать точки в названии репозитория.
Во-вторых, лучше что-то более которкое и отражающее суть содержимого. my-project ни о чем не говорит. Как и parsing comments. Поэтому лучше использовать что-то вроде feedback-analyzer

**Comment by Svichkariov** [comment]
Нужно ли оставлять обратную связь на ваши замечания после исправления?

**Comment by ak-itacademy** [comment]
Нужно еще раз переименовать. Имена репозиториев принято обозначать со строчной буквы, а не с заглавной. Так что используйте, пожалуйста, review-of-comments вместо Review-of-comments
